<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>n</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Neutrino</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.neutrino</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(def)\s+\b(operator\b\s*[+\-&gt;a-z]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.neutrino</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(def)\s+(\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.neutrino</string>
				</dict>
			</dict>
			<key>marker</key>
			<string>--- begin keywords ---</string>
			<key>match</key>
			<string>(protocol)\s+(\w+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(channel|var|native|def|return|operator|if|else|while|new|case|match|as|do|fn|and|or|not|on|raise|protocol|super|static|factory|task|yield)\b</string>
			<key>name</key>
			<string>keyword.control.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|this|null)\b</string>
			<key>name</key>
			<string>constant.language.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(internal)\b</string>
			<key>name</key>
			<string>keyword.other.neutrino</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.underline.neutrino</string>
				</dict>
			</dict>
			<key>marker</key>
			<string>--- end keywords ---</string>
			<key>match</key>
			<string>(\w+):</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>plain.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[+\-&gt;]+</string>
			<key>name</key>
			<string>keyword.operator.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.neutrino</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.neutrino</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.neutrino</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>groups</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.documentation.neutrino</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.neutrino</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(param)\b</string>
					<key>name</key>
					<string>keyword.other.doc.neutrino</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\B\*[^*]*\*\B</string>
					<key>name</key>
					<string>markup.bold.doc.neutrino</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b_[^_]*_\b</string>
					<key>name</key>
					<string>markup.italic.doc.neutrino</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\B=[^=]*=\B</string>
					<key>name</key>
					<string>markup.underline.doc.neutrino</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.neutrino</string>
	<key>uuid</key>
	<string>0D6FB057-AFCF-4E96-B587-119AAA94F879</string>
</dict>
</plist>
