from os.path import join
from buildutils import read_lines_from, apply_items
Import('config target properties prefix')

source_files = read_lines_from('library.list')
program_files = read_lines_from(join('main', 'program.list'))

# Creates a new environment and pre-configure it based on the set
# of configuration items
def create_environment():
  result = Environment(CPPPATH=".")
  apply_items(result, properties)
  return result

env = create_environment()

static_library = env.StaticLibrary(config['name'], source_files)
program = env.Program(config['name'], source_files + program_files)
config[prefix + 'static-library'] = static_library[0]
config[prefix + 'program'] = program[0]
env.Alias(target, [static_library, program])
