from os.path import join, abspath
from buildutils import apply_items
from testutils import run_neutrino_tests
Import('config common prefix properties target build')

# Instantiate the test builders for each configuration
env = common.Copy()
apply_items(env, properties)
env.Append(LIBS = [config[prefix + 'shared-library']])

old_build = build

build = abspath(join(old_build, 'cctest'))
env.SConscript(
  join('cctest', 'SConscript'),
  exports = 'config env target prefix config build',
  duplicate = False
)

build = abspath(join(old_build, 'core'))
env.SConscript(
  join('core', 'SConscript'),
  exports = 'config env target prefix config build',
  duplicate = False
)
