from os.path import join, abspath
from buildutils import apply_items
from testutils import run_neutrino_tests
Import('config common prefix properties target build')

# Instantiate the test builders for each configuration
env = common.Copy()
env.Append(LIBS = [config[prefix + 'static-library']])
apply_items(env, properties)

build = abspath(join(build, 'cctest-build'))
env.SConscript(
  join('cctest', 'SConscript'),
  build_dir = build,
  exports = 'config env target prefix config build',
  duplicate = False
)

build = abspath(join(build, 'core-build'))
env.SConscript(
  join('core', 'SConscript'),
  build_dir = build,
  exports = 'config env target prefix config build',
  duplicate = False
)
