<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>n</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~N</string>
	<key>name</key>
	<string>Neutrino</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.neutrino</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.neutrino</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.neutrino</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(protocol)\b\s+(\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.neutrino</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(def)\b\s+(\w+|\([^)]+\))\.([^ (]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.neutrino</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(def)\b\s+(\w+)\s*\(</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+((r|R)[0-9A-Fa-f]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z][A-Z_]+|k[A-Z]\w*)\b</string>
			<key>name</key>
			<string>constant.other.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w+|\w+_t\b</string>
			<key>name</key>
			<string>storage.type.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;|:=|\b.\b|=&gt;</string>
			<key>name</key>
			<string>non-operator.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[+\-\&amp;&lt;&gt;=*/%.]+</string>
			<key>name</key>
			<string>keyword.other.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(protocol|def|ref)\b</string>
			<key>name</key>
			<string>storage.type.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not|new|is)\b</string>
			<key>name</key>
			<string>keyword.operator.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|for|with_escape|fn|internal|in)\b</string>
			<key>name</key>
			<string>keyword.control.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(this|null|true|false)\b</string>
			<key>name</key>
			<string>variable.language.neutrino</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\w+</string>
			<key>name</key>
			<string>entity.name.tag.neutrino</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.neutrino</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.neutrino</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.neutrino</string>
	<key>uuid</key>
	<string>E9BE656A-A392-424F-AC5D-51829F230FB4</string>
</dict>
</plist>
