from buildutils import apply_items, read_lines_from, read_files_from
from os.path import join, abspath
Import('config common prefix native_properties target build properties')

def get_properties():
  result = { }
  for (key, value) in properties.items():
    result[key.lower()] = value
  return result

# Instantiate the test builders for each configuration
env = common.Copy()
apply_items(env, native_properties)

library_files = read_files_from(get_properties(), join(config['root'], 'natives'), join(config['root'], 'natives', 'library.list'))

shared_library = env.SharedLibrary('core', library_files)
config[prefix + 'natives'] = shared_library[0]
env.Alias(prefix + 'natives', shared_library)
if 'natives' != prefix + 'natives':
  env.Depends('natives', prefix + 'natives')
