import sys
from os.path import dirname, join, basename, exists, abspath

root = dirname(File('SConstruct').rfile().abspath)
sys.path.append(root)
from tools import build, pollock


kOptions = {
  'mode': {
    'values': ['debug', 'release'],
    'default': 'release'
  }
}


def configure(relative_root, build_config, pollock_path):
  opts = Options()
  for (key, value) in kOptions.items():
    opts.Add(EnumOption(key, '', value['default'], allowed_values=value['values']))
  env = Environment(options = opts)
  Help(opts.GenerateHelpText(env))
  options = { }
  for key in kOptions.keys():
    options[key] = env.Dictionary()[key]
  config = build.read_build_file(relative_root, build_config, options)
  pollock_processor = pollock.read_processor(pollock_path)
  SConscript(
    'SConscript',
    exports = 'config pollock_processor options',
    duplicate = False,
    build_dir = 'obj'
  )


configure('.', join(root, 'build'), join(root, 'src', 'pollock'))
